FROM node:lts-alpine
# RUN apk update
# RUN apk add --no-cache ffmpeg
WORKDIR '/app'
RUN apk update
RUN apk add --no-cache ffmpeg
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . .
CMD ["yarn", "start:dev"]
